version: '3.8'
services:
  client-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db-tms
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-tms:5432/TaskManagementSystemDB
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  db-tms:
    image: postgres:14-alpine
    container_name: db-tms
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=TaskManagementSystemDB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password